import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.scss";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Task Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
